Repository ManageIQ/sprint_statistics, pull requests merged in 2020-05, with the labels that each got.

#46 Fix remaining_open PR count in prs_per_repo.rb
  prs_per_repo.rb
Labels: bug

#47 prs_per_repo should work without human interaction
  prs_per_repo.rb
  sprint.rb
  sprint_boundary_iterator.rb
Labels: enhancement

#48 prs_per_repo script should optimize interactions with GitHub
  prs_per_repo.rb
  sprint.rb
Labels: enhancement

#49 Add yaml support to prs_per_repo.rb
  prs_per_repo.rb
Labels: enhancement

#50 Add support for GitHub issues to prs_per_repo script
  prs_per_repo.rb
Labels: enhancement

#51 Extend SprintBoundaryIterator to Sprint 8
  old_sprint_boundaries.yml
  sprint_boundary_iterator.rb
Labels: enhancement

#52 Rename prs_per_repo.rb to github_activity.rb
  github_activity.rb
Labels: refactoring

#53 re-added SprintBoundaryIterator.start_range method
  sprint_boundary_iterator.rb
Labels: bug

#45 Allow the caller to specify start/end and sprint length options.
  Gemfile
  merged_prs_per_sprint.rb
Labels: enhancement

#54 [CodeClimate] Continue when snapshot data is nil
  code_climate.rb
Labels: bug
